// @ts-check

// Xburn 手册侧边栏（深度运营：全量手写，不使用 autogenerated）
// 排序集中在此文件控制，文件不写 sidebar_position，目录不靠 _category_.json position
// 见 url-governance §2.1 第 3 条 + admission-policy §3.4

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    'xburn/overview',
    'xburn/quick-start',
    'xburn/install',
    {
      type: 'category',
      label: '烧录基础',
      items: [
        'xburn/basics/burn-modes',
        'xburn/basics/download-modes-explained',
        'xburn/basics/interface-fields',
        'xburn/basics/storage-media',
        'xburn/basics/firmware-type',
      ],
    },
    {
      type: 'category',
      label: '环境准备',
      items: [
        'xburn/environment/windows-setup',
        'xburn/environment/linux-setup',
        'xburn/environment/mac-setup',
        'xburn/environment/hardware-connection',
      ],
    },
    {
      type: 'category',
      label: '烧录操作',
      items: [
        'xburn/operation/enter-dfu-mode',
        'xburn/operation/enter-fastboot',
        'xburn/operation/full-image-burn',
        'xburn/operation/partial-burn',
        'xburn/operation/backup',
        'xburn/operation/boot-verify',
        'xburn/operation/batch-burn',
      ],
    },
    {
      type: 'category',
      label: '异常处理',
      items: [
        'xburn/troubleshooting/serial-driver',
        'xburn/troubleshooting/boot-issues',
      ],
    },
    {
      type: 'category',
      label: '参考',
      items: [
        'xburn/reference/version-matrix',
        'xburn/reference/model-cheatsheet',
        'xburn/reference/changelog',
      ],
    },
  ],
};

export default sidebars;
