// @ts-check

// XBurn 手册侧边栏（深度运营：全量手写，不使用 autogenerated）
// 排序集中在此文件控制，文件不写 sidebar_position，目录不靠 _category_.json position
// 见 url-governance §2.1 第 3 条 + admission-policy §3.4

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    'whats-new',
    'overview',
    'install',
    {
      type: 'category',
      label: '环境准备',
      items: [
        'environment/windows-setup',
        'environment/linux-setup',
        'environment/mac-setup',
      ],
    },
    {
      type: 'category',
      label: '烧录配置',
      // 6 篇平铺：顺序即用户旅程（看懂字段 → 选连接 → 选介质 → 接几台 → 烧完怎样 → 失败看日志）
      // 不再分基本/高级/日志三层：两个分类各只压 1 篇，层级白增；批量烧录是场景而非配置字段，硬归"高级配置"为误标，平铺后归位难题自动消解
      items: [
        'basics/interface-fields',
        'basics/download-modes',
        'basics/storage-media',
        'basics/batch-burn',
        'basics/auto-reboot',
        'basics/log-settings',
      ],
    },
    {
      type: 'category',
      label: '异常处理',
      items: [
        'troubleshooting/serial-driver',
        'troubleshooting/boot-issues',
      ],
    },
  ],
};

export default sidebars;
